name: test run
on:
  push:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: test
      uses: comet-ml/push-files@main
      with:
        files: '[]'
        github_token: token
